POST http://localhost:3000/api/auth/login
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZWI0OGU3MC03NTMxLTQ2MzQtOTg1Ni01Y2E0ZDQxMDg0ZTkiLCJleHAiOjE3NjQ0MTc4NjMsImlhdCI6MTc2NDQxNjk2MywianRpIjoiOWVlNDA3YmEtNWU4MC00NWYxLWFjMWEtZDFkOWFlMzExMjBkIiwiaXNfb3duZXIiOmZhbHNlLCJpc19zeXN0ZW1fYWRtaW4iOmZhbHNlLCJpc19yb2xlX2FkbWluIjpmYWxzZSwiYXBwX3JvbGVzIjpbXX0.HEhbyTQs88dccS_jDDcMPQ-zyvAM6XIVztItrXW2R9o

{
  "username": "testuser",
  "password": "testpass"
}
###
GET http://localhost:3000/api/auth/whoami
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZWI0OGU3MC03NTMxLTQ2MzQtOTg1Ni01Y2E0ZDQxMDg0ZTkiLCJleHAiOjE3NjQ0MTc3NDMsImlhdCI6MTc2NDQxNjg0MywianRpIjoiZjM1ZTY5MTQtOTI1ZS00MThmLTliNTItNjM3ODQ5YjkzYTQ5IiwiaXNfb3duZXIiOmZhbHNlLCJpc19zeXN0ZW1fYWRtaW4iOmZhbHNlLCJpc19yb2xlX2FkbWluIjpmYWxzZSwiYXBwX3JvbGVzIjpbXX0.-MDscTpWF6HvIzr3QCJpyUr1ID_vrLSVoopredaUZzc

